version: '3.8'

services:
  server:
    image: ghcr.io/russelr00/hr-football-server:latest
    ports:
      - "3001:3001"
    restart: unless-stopped
    environment:
      - PORT=3001
      - PUBLIC_URL=http://13.126.147.154
      - HOST_PASSWORD=deep2026

  client:
    image: ghcr.io/russelr00/hr-football-client:latest
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - server
